#! /usr/bin/env bash

set -euo pipefail

URL="https://api.github.com/notifications?access_token=${GH_NOTIFICATION_TOKEN}"
NUM=$(curl -s "${URL}" | jq ". | length")

echo ""
echo GH
if [ "${NUM}" -gt 0 ]; then
  echo "#99cc99"
else
  echo "#515151"
fi
