#! /usr/bin/env bash

set -euo pipefail

NUM=$(curl -u "benhartley:${GH_NOTIFICATION_TOKEN}" "https://api.github.com/notifications" | jq ". | length")

echo ""
echo GH
if [ "${NUM}" -gt 0 ]; then
  echo "#99cc99"
else
  echo "#515151"
fi
