#! /usr/bin/env bash

set -uo pipefail

INFO=$(amixer -c 1 -MD pulse get Master)

MUTED=$(grep -oP '\[off\]' <<< "$INFO" | uniq | wc -w)
PERCENTAGE=$(grep -oP '\d+%' <<< "$INFO" | uniq)

printf "♪ %s\n" "$PERCENTAGE"
printf "♪ %s\n" "$PERCENTAGE"

if [[ $MUTED = 1 ]]; then
  echo "#ffcc66"
else
  echo "#2d2d2d"
  echo "#ffcc66"
fi
