#!/usr/bin/env bash

set -euo pipefail

function main {
    i3-msg "workspace 1; append_layout /home/btfh/.dotfiles/i3/.i3/workspace-1.json"
    i3-msg "workspace 4; append_layout /home/btfh/.dotfiles/i3/.i3/workspace-4.json"
    i3-msg "workspace 8; append_layout /home/btfh/.dotfiles/i3/.i3/workspace-8.json"

    urxvt -title tmux -e zsh -ic tmux &
    urxvt -title mutt -e zsh -ic mutt &
    urxvt -title weechat -e zsh -ic weechat &
    urxvt -title journal_offlineimap -e zsh -ic "journalctl -ft offlineimap" &

    # kill default tmux session after enough time has passed for auto-restore to kick in
    # this should be left until last
    sleep 5
    tmux kill-session -t 0
}

main
